# version: "3.9"

services:
  db:
    image: postgres:15
    container_name: app_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./apps/backend
    container_name: app_backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/frontend
    container_name: app_frontend
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  postgres_data:

