services:
  training:
    build:
      context: ./backend
    image: backend_training
    ports:
      - "8000:8000"
    volumes:
      - ./backend/best_performance:/backend/best_performance
    tty: true
    stdin_open: true

  backend:
    build:
      context: ./backend
    image: backend
    ports:
      - "8001:8001"
    command:
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8001"

  frontend_test:
    build: ./frontend
    image: frontend_test
    command: ["npm", "run", "test"]

  frontend:
    build:
      context: ./frontend
    image: frontend
    ports:
      - "3000:3000"
    depends_on:
      - frontend_test
