name: Backend CI/CD

on:
  push:
    paths:
      - "apps/backend/**"
      - ".github/workflows/backend.yml"
      - "infra"
  pull_request:
    paths:
      - "apps/backend/**"
      - ".github/workflows/backend.yml"
      - "infra"

env:
  IMAGE_OWNER: yenjung41
  IMAGE_REPO: salary-backend

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/backend

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: setup python
        run: uv python install 3.11

      - name: install dev-dependencies
        run: uv sync --frozen

      - name: run tests
        run: uv run pytest

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.IMAGE_OWNER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: apps/backend
          push: true
          tags: |
            docker.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_REPO }}:${{ github.sha }}
            docker.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: deploy cloud run via IaC
        run: |
          NEW_CLOUDSQL="${{ secrets.CLOUDSQL }}"
          NEW_MODEL_BUCKET="${{ secrets.MODEL_BUCKET }}"
          NEW_DATABASE_URL="${{ secrets.DATABASE_URL }}"
          NEW_GCP_PROJECT="${{ secrets.GCP_PROJECT }}"
          NEW_TRAINING_JOB_NAME="${{ secrets.TRAINING_JOB_NAME }}"
          NEW_IMAGE_BACKEND="docker.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_REPO }}:${{ github.sha }}"

          sed -i "s|CLOUDSQL_IaC|${NEW_CLOUDSQL}|g" infra/gcp/cloud-run-backend.yaml
          sed -i "s|MODEL_BUCKET_IaC|${NEW_MODEL_BUCKET}|g" infra/gcp/cloud-run-backend.yaml
          sed -i "s|DATABASE_URL_IaC|${NEW_DATABASE_URL}|g" infra/gcp/cloud-run-backend.yaml
          sed -i "s|GCP_PROJECT_IaC|${NEW_GCP_PROJECT}|g" infra/gcp/cloud-run-backend.yaml
          sed -i "s|TRAINING_JOB_NAME_IaC|${NEW_TRAINING_JOB_NAME}|g" infra/gcp/cloud-run-backend.yaml
          sed -i "s|IMAGE_BACKEND_IaC|${NEW_IMAGE_BACKEND}|g" infra/gcp/cloud-run-backend.yaml

          gcloud run services replace infra/gcp/cloud-run-backend.yaml \
            --region asia-east1
      # - name: deploy cloud run
      #   run: |
      #     gcloud run deploy salary-backend \
      #       --image docker.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_REPO }}:${{ github.sha }} \
      #       --region asia-east1 \
      #       --add-cloudsql-instances ${{ secrets.CLOUDSQL }} \
      #       --set-env-vars I_AM=backend \
      #       --set-env-vars USE_CLOUD=true \
      #       --set-env-vars MODEL_BUCKET=${{ secrets.MODEL_BUCKET }} \
      #       --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }} \
      #       --set-env-vars GCP_PROJECT=${{ secrets.GCP_PROJECT }} \
      #       --set-env-vars TRAINING_JOB_NAME=${{ secrets.TRAINING_JOB_NAME }} \
      #       --cpu 4 \
      #       --memory 2Gi \
      #       --concurrency 2 \
      #       --min-instances 0 \
      #       --max-instances 2

      - name: deploy cloud job via IaC
        run: |
          NEW_TRAINING_JOB_NAME="${{ secrets.TRAINING_JOB_NAME }}"
          NEW_CLOUDSQL="${{ secrets.CLOUDSQL }}"
          NEW_IMAGE_BACKEND="docker.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_REPO }}:${{ github.sha }}"
          NEW_MODEL_BUCKET="${{ secrets.MODEL_BUCKET }}"
          NEW_DATABASE_URL="${{ secrets.DATABASE_URL }}"

          sed -i "s|TRAINING_JOB_NAME_IaC|${NEW_TRAINING_JOB_NAME}|g" infra/gcp/cloud-job.yaml
          sed -i "s|CLOUDSQL_IaC|${NEW_CLOUDSQL}|g" infra/gcp/cloud-job.yaml
          sed -i "s|IMAGE_BACKEND_IaC|${NEW_IMAGE_BACKEND}|g" infra/gcp/cloud-job.yaml
          sed -i "s|MODEL_BUCKET_IaC|${NEW_MODEL_BUCKET}|g" infra/gcp/cloud-job.yaml
          sed -i "s|DATABASE_URL_IaC|${NEW_DATABASE_URL}|g" infra/gcp/cloud-job.yaml

          gcloud run jobs replace infra/gcp/cloud-job.yaml \
            --region asia-east1
      # - name: Update Cloud Run Job
      #   run: |
      #     gcloud run jobs update ${{ secrets.TRAINING_JOB_NAME }} \
      #       --image docker.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_REPO }}:${{ github.sha }} \
      #       --region asia-east1 \
      #       --add-cloudsql-instances ${{ secrets.CLOUDSQL }} \
      #       --set-env-vars I_AM=jobrun \
      #       --set-env-vars USE_CLOUD=true \
      #       --set-env-vars MODEL_BUCKET=${{ secrets.MODEL_BUCKET }} \
      #       --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }} \
      #       --cpu 8 \
      #       --memory 16Gi \
      #       --task-timeout 3600s \
      #       --max-retries 1 \
      #       --tasks 1 \
      #       --parallelism 1
