name: Backend CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "apps/backend/**"
      - ".github/workflows/backend.yml"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/backend

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: setup python
        run: uv python install 3.11

      - name: install dev-dependencies
        run: uv sync

      - name: run tests
        run: uv run pytest

  deploy:
    needs: test

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: GCP auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: config docker
        run: |
          gcloud auth configure-docker asia-east1-docker.pkg.dev

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push image
        uses: docker/build-push-action@v5
        with:
          context: apps/backend
          push: true
          tags: asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/salary-backend/backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: deploy cloud run
        run: |
          gcloud run deploy salary-backend \
            --image  asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/salary-backend/backend:${{ github.sha }} \
            --region asia-east1 \
            --add-cloudsql-instances ${{ secrets.CLOUDSQL }} \
            --set-env-vars USE_CLOUD=true \
            --set-env-vars MODEL_BUCKET=${{ secrets.MODEL_BUCKET }} \
            --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }} \
            --set-env-vars GCP_PROJECT=${{ secrets.GCP_PROJECT }} \
            --set-env-vars TRAINING_JOB_NAME=${{ secrets.TRAINING_JOB_NAME }} \
            --set-env-vars I_AM="backend" \
            --cpu 2 \
            --memory 1Gi \
            --concurrency 2 \
            --min-instances 0 \
            --max-instances 2 \
            --allow-unauthenticated

      - name: Update Cloud Run Job
        run: |
          gcloud run jobs update ${{ secrets.TRAINING_JOB_NAME }} \
          --image asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/salary-backend/backend:${{ github.sha }} \
          --region asia-east1 \
          --add-cloudsql-instances ${{ secrets.CLOUDSQL }} \
          --set-env-vars I_AM=jobrun \
          --set-env-vars USE_CLOUD=true \
          --set-env-vars MODEL_BUCKET=${{ secrets.MODEL_BUCKET }} \
          --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }} \
          --cpu 8 \
          --memory 16Gi \
          --task-timeout 3600s \
          --max-retries 1 \
          --tasks 1 \
          --parallelism 1
